config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'application#welcome'
  resources :orders
  resources :customers
  resources :drinks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  has_many :drinks, through: :orders
  validates :name, presence: true, uniqueness: true
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_many :orders
  has_many :customers, through: :orders
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :drink
  validates :size, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def welcome
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
   @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    if @customer.valid?
      redirect_to @customer
    else
      flash[:errors] = @customer.errors.full_messages
      redirect_to new_customer_path
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to @customer
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end



  private
  def customer_params
    params.require(:customer).permit(:name)
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  def index
    @drinks = Drink.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
    @customers = Customer.all
    @drinks = Drink.all
  end

  def create
    @order = Order.create(order_params)
    redirect_to @order.customer
  end

  private

  def order_params
    params.require(:order).permit(:drink_id, :customer_id, :size, :reciept)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/application/welcome.html.erb
<h1 id="message">The Cafe</h1>

<div>
  <img src="https://i.pinimg.com/originals/3c/65/c3/3c65c3aafb7249dbf5e5360c3b95e293.gif" alt="coffee" height="340" width="340">
</div>

<div class="menu">
  <%= link_to '<button type="button">Drink Menu</button>'.html_safe, drinks_path %><br>
<br>
  <%= link_to '<button type="button">Our Customers</button>'.html_safe, customers_path %><br>
  <br>
  <%= link_to '<button type="button">Make Order</button>'.html_safe, new_order_path %><br>
</div>

app/views/customers/_form.html.erb
<% if flash[:errors] %>
  <h5>Oh no... (｡•́︿•̀｡)</h5>
    <ul>
      <% flash[:errors].each do |message| %>
        <li>
          <%= message %>
        </li>
      <%end %>
    </ul>
<% end  %>
<br>
<br>

<%= form_for @customer do |f| %>
➱ <%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.submit "Submit"%>
<% end %>

app/views/customers/edit.html.erb
<h1>🌟 Edit <%= @customer.name %> 🌟</h1>

<%= render "form" %>

app/views/customers/index.html.erb
<h1>👤 Customers 👤</h1>
<ul>
  <% @customers.each do |c| %>
    <li>
      ☞ <%= link_to c.name, c %>
    </li>
  <% end %>
</ul>

<%= link_to '<button type="button">Create Customer</button>'.html_safe, new_customer_path %><br>
<br>
<%= link_to '<button type="button">Welcome Page</button>'.html_safe, welcome_path %><br>

app/views/customers/new.html.erb
<h1>🌟 Become A Customer 🌟</h1>

<%= render "form" %>

app/views/customers/show.html.erb
<h1>🥤 <%= @customer.name %> Has Been Drinking 🥤</h1>

<h3>Past Orders:</h3>
<ul>
  <% @orders.each do |order| %>
    <li>
      ☞ Drink: <%= order.drink.name %>
      ❀ Size: <%= order.size %>
      ❀ Reciept?
        <% if order.reciept == true%>
          ❌ no
          <% else %>
          ✅ yes
        <% end %>
    </li>
  <%  end  %>
</ul>

<h4>New Order: </h4>
<%= link_to '<button type="button">Make Order</button>'.html_safe, new_order_path %><br>

<p>∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇ </p>
<%= link_to '<button type="button">Edit Page?</button>'.html_safe, edit_customer_path %><br>
<br>
<%= button_to "Delete #{@customer.name}?", customer_path(@customer), method: :delete, data: { confirm: '(｡•́︿•̀｡) Are you sure?' } %><br>

<%= link_to '<button type="button">Back to Customers</button>'.html_safe, customers_path %>

app/views/drinks/index.html.erb
<h1>📜 Drink Menu 📜</h1>
<ul>
  <% @drinks.each do |d| %>
    <li>
      ♨ <%= d.name %>
    </li>
  <% end  %>
</ul>

<%= link_to '<button type="button">Welcome Page</button>'.html_safe, welcome_path %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheCafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<h1>☕️ Make An Order ☕️</h1>
<%= form_for @order do |f| %>
  <%= f.label "Customer:" %>
    <%= f.collection_select :customer_id, @customers, :id, :name %><br>
  <%= f.label "Pick a drink:" %>
    <%= f.collection_select :drink_id, @drinks, :id, :name %><br>
  <%= f.label "Choose one size: " %><br>
  <%= f.select :size, ["small", "medium", "large"] %><br>
  <%= f.label "Want a reciept?" %>
    <%= f.check_box :reciept %><br>
  <p>∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇∇ </p>
  <%= f.submit "Create Your Order" %>
<% end  %>
<br>
<%= link_to '<button type="button">New Customer?</button>'.html_safe, new_customer_path %><br>
<br>
<%= link_to '<button type="button">Welcome Page</button>'.html_safe, welcome_path %>